specVersion: 1.0.0
name: subquery-leaderboard
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=0.35.2'
  query:
    name: '@subql/query'
    version: '*'
description: 'Season 2 Leaderboard project for Subquery Testnet'
repository: ''
schema:
  file: ./schema.graphql
network:
  chainId: '0x6b18138563ba86208d17839ff4f48e2f1fcaddb520de82bb6a731bcb5e801e85'
  endpoint: wss://sqtn.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/subquery-testnet-dictionary
  chainTypes:
    file: ./dist/chaintypes.js

x-frontier: &frontier
  kind: substrate/FrontierEvm
  startBlock: 1
  processor: &frontier-processor
    file: './dist/frontierEvm.js'
  assets:
    staking:
      file: ./node_modules/@subql/contract-sdk/artifacts/contracts/Staking.sol/Staking.json
    indexerRegistry:
      file: ./node_modules/@subql/contract-sdk/artifacts/contracts/IndexerRegistry.sol/IndexerRegistry.json
    queryRegistry:
      file: ./node_modules/@subql/contract-sdk/artifacts/contracts/QueryRegistry.sol/QueryRegistry.json
    planManager:
      file: ./node_modules/@subql/contract-sdk/artifacts/contracts/PlanManager.sol/PlanManager.json
    serviceAgreementRegistry:
      file: ./node_modules/@subql/contract-sdk/artifacts/contracts/ServiceAgreementRegistry.sol/ServiceAgreementRegistry.json
    rewardsDistributor:
      file: ./node_modules/@subql/contract-sdk/artifacts/contracts/RewardsDistributer.sol/RewardsDistributer.json

dataSources:
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: indexerRegistry
        address: '0xe5B4EA276e1030F55790bB8695bC1f8362241bb9'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleUnregisterIndexer
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - UnregisterIndexer(address indexed indexer)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: staking
        address: '0x2F50025987C58549018841e007c61759d8Fb9BeD'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleAddDelegation
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - DelegationAdded(address indexed source, address indexed indexer, uint256 amount)
        - handler: handleRemoveDelegation
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - DelegationRemoved(address indexed source, address indexed indexer, uint256 amount)
        - handler: handleWithdrawClaimed
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - UnbondWithdrawn(address indexed source, uint256 amount, uint256 index)
        - handler: handleSetCommissionRate
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - SetCommissionRate(address indexed indexer, uint256 amount)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: queryRegistry
        address: '0xD85888D978e014ad9dA7cf011E726B04FBf0c63c'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleIndexingReady
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - UpdateIndexingStatusToReady(address indexer, bytes32 deploymentId)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: planManager
        address: '0xA913e483B6B6f9607CcC1E083928342b2d5d36aF'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handlePlanCreated
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - PlanCreated(address indexed creator, bytes32 indexed deploymentId, uint256 planTemplateId, uint256 planId, uint256 price)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: serviceAgreementRegistry
        address: '0xd098AaCe6495745496428085be2976391C6A5bC4'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleServiceAgreementCreated
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - ServiceAgreementCreated(address indexed consumer, address indexed indexer, bytes32 indexed deploymentId, address serviceAgreement)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: rewardsDistributor
        address: '0xA500a3ad54223B7E18D7d73da34f2EF06aCa77eC'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleRewardsClaimed
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - ClaimRewards(address indexed indexer, address indexed delegator, uint256 rewards)
